config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  get '/about', to: 'main#about'
  resources :songs, only: [:new, :create, :show]

  resources :sources, only: [:new, :create]
  resources :lines, only: [:index]
  resources :lyrics, only: [:index]
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates_presence_of :rhythm1, :rhythm2
  has_many :sections

  def measures
    self.melody.length / self.beats_in_measure
  end

  def melody
    self.sections.map(&:pattern).join('').split('')
  end

  def bass
    self.sections.map(&:bass_notes).flatten
  end

  def title
    self.sections.first.lyrics.split(' ')[0..1].join(' ').titleize
  end

  def to_midi
    midi_song = MIDI::Sequence.new
    meta_track = MIDI::Track.new(midi_song)
    midi_song.tracks << meta_track
    meta_track.events << MIDI::ProgramChange.new(0, 0)

    melody = MIDI::Track.new(midi_song)
    bass = MIDI::Track.new(midi_song)
    midi_song.tracks << melody
    midi_song.tracks << bass
    eighth_note_length = midi_song.note_to_delta('eighth')

    melody.events << MIDI::NoteOn.new(0, 0, 127, 0)
    melody.events << MIDI::NoteOff.new(0, 0, 127, eighth_note_length)
    bass.events << MIDI::NoteOn.new(0, 0, 127, 0)
    bass.events << MIDI::NoteOff.new(0, 0, 127, eighth_note_length)

    offset = 0

    self.melody.each do |note|
      if note == "."
        offset += eighth_note_length
      else
        melody_note = 64 + note.to_i
        melody.events << MIDI::NoteOn.new(0, melody_note, 127, offset)
        melody.events << MIDI::NoteOff.new(0, melody_note, 127, eighth_note_length)
        offset = 0
      end
    end

    self.bass.each do |bass_interval|
      note = 40 + bass_interval.to_i
      bass.events << MIDI::NoteOn.new(0, note, 127, 0)
      bass.events << MIDI::NoteOff.new(0, note, 127, eighth_note_length*self.beats_in_measure)
    end

    file = File.new('tmp/midifile.mid', 'wb')
    midi_song.write(file)
    file
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @lyrics_sources = allowed_sources.keys
  end

  def create
    lyricist = Lyricist.from_source_file(lyrics_source)

    songwriter = Songwriter.new(lyricist)
    songwriter.build_default_sections
    redirect_to song_path(songwriter.song)
  end

  def show
    @song = Song.find(params[:id])
    respond_to do |format|
      format.html
      format.mid { send_file @song.to_midi, type: "audio/midi" }
    end
  end

  private

  def lyrics_source
    source = params[:lyrics_source]
    return unless allowed_sources.keys.include?(source)
    allowed_sources[source]
  end

  def allowed_sources
    {
      'Dog (Wiki Page)' => :dog_wiki_page,
      'Moby Dick' => :moby_dick,
      'Edgar Allen Poe' => 'edgar_allen_poe'
    }
  end
end

app/views/songs/new.html.haml
.container
  .row
    .col-sm-12
      .text-center
        %h2 Welcome to Songer
        %p Click below to generate a new song
        = simple_form_for(Song.new) do |form|
          %p
            %label
              Lyrics Source
              %select.form-control(name='lyrics_source')
                - @lyrics_sources.each do |source|
                  %option{value: source}= source
          = form.button :submit, "Create song", class: 'btn btn-primary btn-lg'
        %br
        = link_to 'About Songer', about_path

app/views/songs/show.html.haml
.song(ng-controller="SongCtrl as ctrl")
  .container
    .row
      .col-sm-12
        = link_to "< Back", new_song_path
    .row
      .col-sm-12
        %h2= @song.title
    .row
      .col-sm-12
        %button.btn.btn-primary.hidden-xs(data-loading-text="Loading..." ng-click="ctrl.startPlayback($event, '#{song_url(@song, format: :mid)}')") Play
        %button.btn.btn-default.hidden-xs= link_to "Download as MIDI", song_path(@song, format: :mid)
    .row
      .col-sm-12
        .lyrics
          %h3.hidden-xs Lyrics
          - @song.sections.each do |section|
            %p
              - section.lyrics_words.each do |word|
                %span.word{'data-syllables' => word.syllables}= word.value

        .visible-xs
          %br
          %em Playback is currently disabled on mobile devices